# Generated by Django 2.2.12 on 2020-05-22 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='baby_product',
            field=models.BooleanField(default=False, verbose_name='Produit pour enfant'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('A', 'Alimentation'), ('P', 'Pharmacie'), ('Q', 'Quotidien'), ('NA', 'Non-attribué')], default='NA', max_length=2, verbose_name='Catégorie'),
        ),
    ]
