# Generated by Django 2.2.12 on 2020-05-22 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='stripe_id',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bebes',
            field=models.IntegerField(default=0, verbose_name="nombre d'enfants de moins de 4 ans"),
        ),
    ]
