# Generated by Django 2.2.12 on 2020-05-14 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='stripe_id',
        ),
    ]
